# Generated by Django 3.2.25 on 2025-07-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='front_name',
            new_name='friendly_name',
        ),
    ]
